variables:
  GIT_STRATEGY: clone

configure-build-test:
  stage: build
  before_script:
    - git submodule update --init --recursive
  script:
    - source /projects/sems/modulefiles/utils/sems-archive-modules-init.sh
    - module load acme-env
    - module load sems-archive-git/2.10.1
    - module load sems-archive-cmake/3.19.1
    - module load acme-gcc/8.1.0
    - module load acme-openmpi/2.1.5
    - module load acme-hdf5/1.12.0/acme
    - module load acme-netcdf/4.7.4/acme
    - mkdir build
    - cd build
    - ../scripts/configure/configure-cldera-tools-runner.sh ../ | tee ../runner_log.txt
    - make -j4 | tee -a ../runner_log.txt
    - ctest --output-on-failure | tee -a ../runner_log.txt

  artifacts:
    paths:
      - runner_log.txt
