variables:
  GIT_STRATEGY: clone

configure-build-test:
  stage: build
  before_script:
    - git submodule update --init --recursive
  script:
    - source scripts/env/load-modules-vaporwave.sh
    - mkdir build
    - cd build
    - ../scripts/configure/configure-cldera-tools-runner.sh ../ | tee ../runner_log.txt
    - make -j4 | tee -a ../runner_log.txt
    - ctest --output-on-failure | tee -a ../runner_log.txt

  artifacts:
    paths:
      - runner_log.txt
