variables:
  GIT_STRATEGY: clone

configure-build-test:
  stage: build
  before_script:
    - |-
      if [ $CI_RUNNER_ID == 121 ]; then
        MACH_NAME=s1007989
      elif [ $CI_RUNNER_ID == 48 ]; then
        MACH_NAME=s1007989
      else
        exit 1
      fi
    - env | grep MACH_NAME
    - git submodule update --init --recursive
    - source scripts/env/load-modules-${MACH_NAME}.sh
  script:
    - mkdir build
    - cd build
    - ../scripts/configure/configure-cldera-tools-runner.sh ../ | tee ../runner_log.txt
    - make -j4 | tee -a ../runner_log.txt
    - ctest --output-on-failure | tee -a ../runner_log.txt

  artifacts:
    paths:
      - runner_log.txt
