#########################################
#      CLDERA CONFIG FILE TEMPLATE      #
#                                       #
#  This file (with this name!) must be  #
#  placed inside the case folder, or    #
#  the profiling tool will do nothing.  #
#                                       #
#########################################
%YAML 1.0
---
Profiling Output:
  Filename: cldera_stats.nc
  Flush Frequency: 10
Fields To Track: [SO2, H2SO4]

SO2:
  Compute Stats: [global_max]
H2SO4:
  Compute Stats: [global_min]
...
