#########################################
#      CLDERA CONFIG FILE TEMPLATE      #
#                                       #
#  This file (with this name!) must be  #
#  placed inside the case folder, or    #
#  the profiling tool will do nothing.  #
#                                       #
#########################################
%YAML 1.0
---
Add Compute Stats Barrier: false
Timing Filename: my_timings.txt
Profiling Output:
  Filename: cldera_stats.nc
  Flush Frequency: 10
  Enable Output: true
  Save Geometry Fields: true
Fields To Track: [SO2, SULFATE]

SO2:
  Compute Stats: [tropo_anomaly]
  tropo_anomaly:
    type: pipe
    inner:
      type: vertical_contraction
      average: true
      level_bounds: [60,72]
    outer:
      type: masked_integral
      mask_field: mask
      mask_file_name: /path/to/ipcc-mask-file.nc
      weight_field: area
      average: true
SULFATE:
  Compute Stats: [global_min]
...
