#########################################
#      CLDERA CONFIG FILE TEMPLATE      #
#                                       #
#  This file (with this name!) must be  #
#  placed inside the case folder, or    #
#  the profiling tool will do nothing.  #
#                                       #
#########################################
%YAML 1.0
---
Add Compute Stats Barrier: false
Timing Filename: my_timings.txt
Profiling Output:
  Filename: cldera_stats.nc
  Flush Frequency: 10
  Enable Output: true
  Save Geometry Fields: true
Fields To Track: [SO2, SULFATE]

SO2:
  Compute Stats: [tropo_anomaly]
  tropo_anomaly:
    type: piped
    outer:
      type: vertical_integral
      average: true
      level_bounds: [1,10]
    inner:
      type: zonal_mean
      Latitude Bounds: [-40.0, 40.0]
SULFATE:
  Compute Stats: [global_min]
...
